// Curated resource library: loads the bundled manifest (generated by
// scripts/build-library.mjs into public/library/) and resolves card image URLs.
// Cards are served as same-origin static files, so they display and export
// (PNG/MP4 canvas) without CORS taint.

export interface LibraryCard {
  id: string;        // "<categoryId>/<slug>"
  name: string;      // display name
  file: string;      // BASE_URL-relative, e.g. "library/gems/amethyst.webp" (light layer for cards)
  fileDark?: string; // card line-art: dark-theme layer (white ink). Absent for center mandalas.
}

export interface LibraryCategory {
  id: string;
  label: string;
  kind: 'card' | 'center';
  cards: LibraryCard[];
}

export interface LibraryManifest {
  generatedAt: string;
  categories: LibraryCategory[];
}

// Resolve a manifest-relative file to a loadable URL under the app's base path
// ("/" in dev, "/QRP-dgby/" in the GitHub Pages build).
export const libraryImageUrl = (file: string): string =>
  `${import.meta.env.BASE_URL}${file}`;

let cache: Promise<LibraryManifest> | null = null;

// Fetch and memoize the library manifest. Rejects if it can't be loaded so the
// caller can surface an error (e.g. the library wasn't built/bundled).
export const loadLibraryManifest = (): Promise<LibraryManifest> => {
  if (!cache) {
    cache = fetch(`${import.meta.env.BASE_URL}library/manifest.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`Failed to load library (${res.status})`);
        return res.json() as Promise<LibraryManifest>;
      })
      .catch((err) => {
        cache = null; // allow retry on next open
        throw err;
      });
  }
  return cache;
};
